# Tasks
Conduct exploratory data analysis (EDA) using Pandas and Matplotlib

In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
pd.options.display.mpl_style='default'

df=pd.read_csv("./Cars.csv")
print (df.head())

    Make            Model   Type Origin DriveTrain     MSRP  Invoice  \
0  Acura              MDX    SUV   Asia        All  $36,945  $33,337
1  Acura   RSX Type S 2dr  Sedan   Asia      Front  $23,820  $21,761
2  Acura          TSX 4dr  Sedan   Asia      Front  $26,990  $24,647
3  Acura           TL 4dr  Sedan   Asia      Front  $33,195  $30,299
4  Acura       3.5 RL 4dr  Sedan   Asia      Front  $43,755  $39,014

   EngineSize  Cylinders  Horsepower  MPG_City  MPG_Highway  Weight  \
0         3.5          6         265        17           23    4451
1         2.0          4         200        24           31    2778
2         2.4          4         200        22           29    3230
3         3.2          6         270        20           28    3575
4         3.5          6         225        18           24    3880

   Wheelbase  Length
0        106     189
1        101     172
2        105     183
3        108     186
4        115     197

In [6]:
df.describe()

,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
count,428.000000,426.000000,428.000000,428.000000,428.000000,428.000000,428.000000,428.000000
mean,3.196729,5.807512,215.885514,20.060748,26.843458,3577.953271,108.154206,186.362150
std,1.108595,1.558443,71.836032,5.238218,5.741201,758.983215,8.311813,14.357991
min,1.300000,3.000000,73.000000,10.000000,12.000000,1850.000000,89.000000,143.000000
25%,2.375000,4.000000,165.000000,17.000000,24.000000,3104.000000,103.000000,178.000000
50%,3.000000,6.000000,210.000000,19.000000,26.000000,3474.500000,107.000000,187.000000
75%,3.900000,6.000000,255.000000,21.250000,29.000000,3977.750000,112.000000,194.000000
max,8.300000,12.000000,500.000000,60.000000,66.000000,7190.000000,144.000000,238.000000

In [21]:
df[df.Horsepower>250]

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
0,Acura,MDX,SUV,Asia,All,"$36,945","$33,337",3.5,6,265,17,23,4451,106,189
3,Acura,TL 4dr,Sedan,Asia,Front,"$33,195","$30,299",3.2,6,270,20,28,3575,108,186
6,Acura,NSX coupe 2dr manual S,Sports,Asia,Rear,"$89,765","$79,978",3.2,6,290,17,24,3153,100,174
17,Audi,A6 4.2 Quattro 4dr,Sedan,Europe,All,"$49,690","$44,936",4.2,8,300,17,24,4024,109,193
18,Audi,A8 L Quattro 4dr,Sedan,Europe,All,"$69,190","$64,740",4.2,8,330,17,24,4399,121,204
19,Audi,S4 Quattro 4dr,Sedan,Europe,All,"$48,040","$43,556",4.2,8,340,14,20,3825,104,179
20,Audi,RS 6 4dr,Sports,Europe,Front,"$84,600","$76,417",4.2,8,450,15,22,4024,109,191
25,Audi,S4 Avant Quattro,Wagon,Europe,All,"$49,090","$44,446",4.2,8,340,15,21,3936,104,179
27,BMW,X5 4.4i,SUV,Europe,All,"$52,195","$47,720",4.4,8,325,16,22,4824,111,184
38,BMW,545iA 4dr,Sedan,Europe,Rear,"$54,995","$50,270",4.4,8,325,18,26,3814,114,191
39,BMW,745i 4dr,Sedan,Europe,Rear,"$69,195","$63,190",4.4,8,325,18,26,4376,118,198
40,BMW,745Li 4dr,Sedan,Europe,Rear,"$73,195","$66,830",4.4,8,325,18,26,4464,123,204
41,BMW,M3 coupe 2dr,Sports,Europe,Rear,"$48,195","$44,170",3.2,6,333,16,24,3415,108,177
42,BMW,M3 convertible 2dr,Sports,Europe,Rear,"$56,595","$51,815",3.2,6,333,16,23,3781,108,177
46,Buick,Rainier,SUV,USA,All,"$37,895","$34,357",4.2,6,275,15,21,4600,113,193
55,Cadillac,Escalade,SUV,USA,Front,"$52,795","$48,377",5.3,8,295,14,18,5367,116,199
56,Cadillac,SRX V8,SUV,USA,Front,"$46,995","$43,523",4.6,8,320,16,21,4302,116,195
57,Cadillac,CTS VVT 4dr,Sedan,USA,Rear,"$30,835","$28,575",3.6,6,255,18,25,3694,113,190
58,Cadillac,Deville 4dr,Sedan,USA,Front,"$45,445","$41,650",4.6,8,275,18,26,3984,115,207
59,Cadillac,Deville DTS 4dr,Sedan,USA,Front,"$50,595","$46,362",4.6,8,300,18,26,4044,115,207
60,Cadillac,Seville SLS 4dr,Sedan,USA,Front,"$47,955","$43,841",4.6,8,275,18,26,3992,112,201
61,Cadillac,XLR convertible 2dr,Sports,USA,Rear,"$76,200","$70,546",4.6,8,320,17,25,3647,106,178
62,Cadillac,Escalade EXT,Truck,USA,All,"$52,975","$48,541",6.0,8,345,13,17,5879,130,221
63,Chevrolet,Suburban 1500 LT,SUV,USA,Front,"$42,735","$37,422",5.3,8,295,14,18,4947,130,219
64,Chevrolet,Tahoe LT,SUV,USA,All,"$41,465","$36,287",5.3,8,295,14,18,5050,116,197
65,Chevrolet,TrailBlazer LT,SUV,USA,Front,"$30,295","$27,479",4.2,6,275,16,21,4425,113,192
82,Chevrolet,Corvette 2dr,Sports,USA,Rear,"$44,535","$39,068",5.7,8,350,18,25,3246,105,180
83,Chevrolet,Corvette convertible 2dr,Sports,USA,Rear,"$51,535","$45,193",5.7,8,350,18,25,3248,105,180
84,Chevrolet,Avalanche 1500,Truck,USA,All,"$36,100","$31,689",5.3,8,295,14,18,5678,130,222
87,Chevrolet,Silverado SS,Truck,USA,All,"$40,340","$35,399",6.0,8,300,13,17,4804,144,238
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
269,Mercedes-Benz,SL500 convertible 2dr,Sports,Europe,Rear,"$90,520","$84,325",5.0,8,302,16,23,4065,101,179
270,Mercedes-Benz,SL55 AMG 2dr,Sports,Europe,Rear,"$121,770","$113,388",5.5,8,493,14,21,4235,101,179
271,Mercedes-Benz,SL600 convertible 2dr,Sports,Europe,Rear,"$126,670","$117,854",5.5,12,493,13,19,4429,101,179
273,Mercedes-Benz,SLK32 AMG 2dr,Sports,Europe,Rear,"$56,170","$52,289",3.2,6,349,17,22,3220,95,158
276,Mercedes-Benz,E500,Wagon,Europe,All,"$60,670","$56,474",5.0,8,302,16,24,4230,112,190
283,Mercury,Marauder 4dr,Sedan,USA,Rear,"$34,495","$31,558",4.6,8,302,17,23,4195,115,212
297,Mitsubishi,Lancer Evolution 4dr,Sports,Asia,Front,"$29,562","$27,466",2.0,4,271,18,26,3263,103,179
299,Nissan,Pathfinder Armada SE,SUV,Asia,Front,"$33,840","$30,815",5.6,8,305,13,19,5013,123,207
307,Nissan,Maxima SE 4dr,Sedan,Asia,Front,"$27,490","$25,182",3.5,6,265,20,28,3473,111,194
308,Nissan,Maxima SL 4dr,Sedan,Asia,Front,"$29,440","$26,966",3.5,6,265,20,28,3476,111,194
311,Nissan,350Z coupe 2dr,Sports,Asia,Rear,"$26,910","$25,203",3.5,6,287,20,26,3188,104,169
312,Nissan,350Z Enthusiast convertible 2dr,Sports,Asia,Rear,"$34,390","$31,845",3.5,6,287,20,26,3428,104,169
314,Nissan,Titan King Cab XE,Truck,Asia,All,"$26,650","$24,926",5.6,8,305,14,18,5287,140,224
325,Pontiac,Bonneville GXP 4dr,Sedan,USA,Front,"$35,995","$32,997",4.6,8,275,17,20,3790,112,203
328,Pontiac,GTO 2dr,Sports,USA,Rear,"$33,500","$30,710",5.7,8,340,16,20,3725,110,190
330,Porsche,Cayenne S,SUV,Europe,All,"$56,665","$49,865",4.5,8,340,14,18,4950,112,188
331,Porsche,911 Carrera convertible 2dr (coupe),Sports,Europe,Rear,"$79,165","$69,229",3.6,6,315,18,26,3135,93,175
332,Porsche,911 Carrera 4S coupe 2dr (convert),Sports,Europe,All,"$84,165","$72,206",3.6,6,315,17,24,3240,93,175
333,Porsche,911 Targa coupe 2dr,Sports,Europe,Rear,"$76,765","$67,128",3.6,6,315,18,26,3119,93,175
334,Porsche,911 GT2 2dr,Sports,Europe,Rear,"$192,465","$173,560",3.6,6,477,17,24,3131,93,175
336,Porsche,Boxster S convertible 2dr,Sports,Europe,Rear,"$52,365","$45,766",3.2,6,258,18,26,2911,95,170
361,Subaru,Impreza WRX STi 4dr,Sports,Asia,All,"$31,545","$29,130",2.5,4,300,18,24,3263,100,174
377,Toyota,Land Cruiser,SUV,Asia,All,"$54,765","$47,986",4.7,8,325,13,17,5390,112,193
410,Volkswagen,Passat W8 4MOTION 4dr,Sedan,Europe,Front,"$39,235","$36,052",4.0,8,270,18,25,3953,106,185
411,Volkswagen,Phaeton 4dr,Sedan,Europe,Front,"$65,000","$59,912",4.2,8,335,16,22,5194,118,204
412,Volkswagen,Phaeton W12 4dr,Sedan,Europe,Front,"$75,000","$69,130",6.0,12,420,12,19,5399,118,204
415,Volkswagen,Passat W8,Wagon,Europe,Front,"$40,235","$36,956",4.0,8,270,18,25,4067,106,184
416,Volvo,XC90 T6,SUV,Europe,All,"$41,250","$38,851",2.9,6,268,15,20,4638,113,189
420,Volvo,S60 R 4dr,Sedan,Europe,All,"$37,560","$35,382",2.5,5,300,18,25,3571,107,181
425,Volvo,S80 T6 4dr,Sedan,Europe,Front,"$45,210","$42,573",2.9,6,268,19,26,3653,110,190

In [24]:
df[1:10]

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
1,Acura,RSX Type S 2dr,Sedan,Asia,Front,"$23,820","$21,761",2.0,4,200,24,31,2778,101,172
2,Acura,TSX 4dr,Sedan,Asia,Front,"$26,990","$24,647",2.4,4,200,22,29,3230,105,183
3,Acura,TL 4dr,Sedan,Asia,Front,"$33,195","$30,299",3.2,6,270,20,28,3575,108,186
4,Acura,3.5 RL 4dr,Sedan,Asia,Front,"$43,755","$39,014",3.5,6,225,18,24,3880,115,197
5,Acura,3.5 RL w/Navigation 4dr,Sedan,Asia,Front,"$46,100","$41,100",3.5,6,225,18,24,3893,115,197
6,Acura,NSX coupe 2dr manual S,Sports,Asia,Rear,"$89,765","$79,978",3.2,6,290,17,24,3153,100,174
7,Audi,A4 1.8T 4dr,Sedan,Europe,Front,"$25,940","$23,508",1.8,4,170,22,31,3252,104,179
8,Audi,A41.8T convertible 2dr,Sedan,Europe,Front,"$35,940","$32,506",1.8,4,170,23,30,3638,105,180
9,Audi,A4 3.0 4dr,Sedan,Europe,Front,"$31,840","$28,846",3.0,6,220,20,28,3462,104,179

In [27]:
graph=df.Make.value_counts().plot(kind='barh')
graph

In [28]:
data=np.array(df[['Make','Horsepower']])
plt.hist(data['Horsepower'], bins, histtype='bar', rwidth=0.8)

ImportError: No module named kernelapp